import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-full`}>
        <div className="flex flex-col overflow-x-clip bg-pink-100">
          <NavBar />
          <main className="flex flex-grow flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
}
